# argunix NixOS module.
#
# Deploys an argunix CI daemon against one or more GitHub / GitLab /
# Forgejo repos. Reloads in place via `Type=notify-reload` and
# `ExecReload=argunixctl reload`. Runs as a static `argunix` user
# (not `DynamicUser`) so it can be added to nix's `trusted-users` for
# local build dispatch.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.argunix;

  yamlFormat = pkgs.formats.yaml { };

  settingsFile =
    if cfg.configFile != null then cfg.configFile else yamlFormat.generate "argunix.yaml" cfg.settings;
in
{
  options.services.argunix = {
    enable = lib.mkEnableOption "the argunix CI daemon";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.argunix;
      defaultText = lib.literalExpression "pkgs.argunix";
      description = "The argunix package to run.";
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "argunix";
      description = ''
        System user the daemon runs as. The user is added to nix's
        `trusted-users` so argunix can dispatch builds via the local
        nix-daemon. Stays static (not `DynamicUser`) for that reason.
      '';
    };

    group = lib.mkOption {
      type = lib.types.str;
      default = "argunix";
      description = "System group for the argunix user.";
    };

    listen = lib.mkOption {
      type = lib.types.str;
      default = "127.0.0.1:8080";
      description = ''
        `host:port` the HTTP server listens on. Overrides any `listen`
        field in the YAML config.
      '';
    };

    openFirewall = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to open the listen port in the firewall. Most deployments
        front argunix with a reverse proxy and leave this false.
      '';
    };

    stateDir = lib.mkOption {
      type = lib.types.path;
      default = "/var/lib/argunix";
      description = ''
        Working directory of the daemon. All relative paths in the YAML
        (`./db.sqlite`, `./logs`, `./work`) resolve against this. Created
        and chowned to `cfg.user` by `StateDirectory=`.
      '';
    };

    settings = lib.mkOption {
      inherit (yamlFormat) type;
      default = { };
      description = ''
        Inline argunix configuration. Converted to YAML and written to the
        store at activation time. Mutually exclusive with `configFile`.

        Reference secrets by absolute path. The daemon runs as a static
        `argunix` user, so any file readable by that user (e.g. an
        agenix/sops secret declared with `owner = "argunix"`) is fine
        — the sandbox does not block `/run/agenix`, `/run/secrets`, or
        `/var/lib/*`.
      '';
      example = lib.literalExpression ''
        {
          external_url = "https://argunix.example.com";
          forges.github-myorg = {
            kind = "github";
            web_url = "https://github.com";
            token_path = "/run/agenix/argunix-github-token";
            # Webhook secrets are auto-generated by argunix per repo,
            # stored in sqlite, and pushed to the forge alongside the
            # hook itself. No operator-managed webhook_secret_path.
            repos."myorg/myrepo" = {
              watched_branches = [ "main" ];
            };
          };
        }
      '';
    };

    configFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = ''
        Path to a pre-existing YAML config. If set, `settings` is ignored.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = !(cfg.configFile != null && cfg.settings != { });
        message = ''
          services.argunix: set either `settings` or `configFile`, not both.
        '';
      }
    ];

    services.argunix.settings = lib.mkIf (cfg.configFile == null) {
      web.static_dir = lib.mkDefault "${cfg.package}/share/argunix/static";
    };

    environment.systemPackages = [ cfg.package ];

    users.users.${cfg.user} = {
      isSystemUser = true;
      inherit (cfg) group;
      description = "argunix CI daemon";
      home = cfg.stateDir;
    };
    users.groups.${cfg.group} = { };

    nix.settings.trusted-users = [ cfg.user ];

    systemd.tmpfiles.rules = [
      "d /nix/var/nix/gcroots/per-user/${cfg.user} 0755 ${cfg.user} ${cfg.group} - -"
    ];

    networking.firewall.allowedTCPPorts =
      let
        httpPort = lib.toInt (lib.last (lib.splitString ":" cfg.listen));
        builderListen = cfg.settings.builder_enrollment.listen or null;
        # Strip optional `[ipv6]:` / `host:` prefix; the port is always
        # the part after the final colon.
        builderPort =
          if builderListen != null then lib.toInt (lib.last (lib.splitString ":" builderListen)) else null;
      in
      lib.optional cfg.openFirewall httpPort ++ lib.optional (builderPort != null) builderPort;

    systemd.services.argunix = {
      description = "argunix CI daemon";
      after = [
        "network-online.target"
        "nix-daemon.service"
      ];
      wants = [ "network-online.target" ];
      wantedBy = [ "multi-user.target" ];

      path = [
        pkgs.git
        pkgs.nix
        pkgs.nix-eval-jobs
        # `nix copy --from ssh-ng://localhost?remote-program=…` invokes
        # a tiny shell wrapper that execs `socat` to bridge stdio to
        # our russh-tunneled proxy socket.
        # see `closure_xfer::nix_copy_over_pool`.
        pkgs.socat
      ];

      serviceConfig = {
        Type = "notify-reload";
        NotifyAccess = "main";
        ExecStart = lib.concatStringsSep " " [
          (lib.getExe' cfg.package "argunix")
          "serve"
          "--config"
          settingsFile
          "--listen"
          cfg.listen
        ];
        ExecReload = lib.concatStringsSep " " [
          (lib.getExe' cfg.package "argunixctl")
          "reload"
          "--config"
          settingsFile
        ];
        Restart = "on-failure";
        RestartSec = 5;

        User = cfg.user;
        Group = cfg.group;

        StateDirectory = "argunix";
        StateDirectoryMode = "0750";
        WorkingDirectory = cfg.stateDir;
        RuntimeDirectory = "argunix";
        LogsDirectory = "argunix";

        # `ProtectSystem=strict` makes the rest of the FS read-only.
        # Punch a single hole for the GC roots argunix creates after every
        # successful build, without giving it write access to any
        # other path under /nix/var.
        ReadWritePaths = [
          "/nix/var/nix/gcroots/per-user/${cfg.user}"
        ];

        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        PrivateDevices = true;
        ProtectKernelTunables = true;
        ProtectKernelModules = true;
        ProtectKernelLogs = true;
        ProtectControlGroups = true;
        ProtectClock = true;
        ProtectHostname = true;
        ProtectProc = "invisible";
        RestrictNamespaces = true;
        RestrictRealtime = true;
        RestrictSUIDSGID = true;
        LockPersonality = true;
        RestrictAddressFamilies = [
          "AF_UNIX"
          "AF_INET"
          "AF_INET6"
        ];
        SystemCallArchitectures = "native";
        UMask = "0027";
      };
    };
  };

  meta.maintainers = [ ];
}
