[workspace]
resolver = "2"
members = [
  "argunix-domain",
  "argunix-nom",
  "argunix-config",
  "argunix-store",
  "argunix-forge",
  "argunix-eval",
  "argunix-build",
  "argunix-registry",
  "argunix-effects",
  "argunix-sched",
  "argunix-web",
  "argunix-control",
  "argunix-builders",
  "argunix-builder",
  "argunix-daemon",
  "argunixctl",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "GPL-3.0-or-later"

[workspace.dependencies]
argunix-domain = { path = "argunix-domain" }
argunix-nom = { path = "argunix-nom" }
argunix-config = { path = "argunix-config" }
argunix-store = { path = "argunix-store" }
argunix-registry = { path = "argunix-registry" }
argunix-effects = { path = "argunix-effects" }

serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
thiserror = "2"
anyhow = "1"
async-trait = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
chrono = { version = "0.4", default-features = false, features = [
  "serde",
  "clock",
  "std",
] }

tokio = { version = "1", features = [
  "macros",
  "rt-multi-thread",
  "fs",
  "io-util",
  "process",
  "signal",
  "sync",
  "time",
] }
sqlx = { version = "0.8", default-features = false, features = [
  "runtime-tokio",
  "sqlite",
  "chrono",
  "macros",
  "migrate",
] }

clap = { version = "4", features = ["derive"] }
tempfile = "3"
zstd = { version = "0.13", default-features = false }
tar = "0.4"
flate2 = "1"
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
base64 = "0.22"
rand = "0.8"
arc-swap = "1"
sd-notify = "0.4"
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "rustls-tls",
] }
wiremock = "0.6"
axum = { version = "0.8", default-features = false, features = [
  "http1",
  "json",
  "tokio",
] }
tower-http = { version = "0.6", default-features = false, features = ["fs"] }
askama = "0.12"
bytes = "1"
russh = "0.60"
socket2 = { version = "0.5", features = ["all"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
