[package]
name = "argunix-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "argunix"
path = "src/main.rs"

[dependencies]
argunix-build = { path = "../argunix-build" }
argunix-builders = { path = "../argunix-builders" }
argunix-config = { workspace = true }
argunix-control = { path = "../argunix-control" }
argunix-domain = { workspace = true }
argunix-effects = { workspace = true }
argunix-eval = { path = "../argunix-eval" }
argunix-forge = { path = "../argunix-forge" }
argunix-nom = { workspace = true }
argunix-registry = { workspace = true }
argunix-sched = { path = "../argunix-sched" }
argunix-store = { workspace = true }
argunix-web = { path = "../argunix-web" }
arc-swap = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
russh = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
sd-notify = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
