[package]
name = "argunix-effects"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
argunix-domain = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
