[package]
name = "argunix-effects"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
argunix-domain = { workspace = true }
async-trait = { workspace = true }
flate2 = { workspace = true }
serde_json = { workspace = true }
tar = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
