[package]
name = "medusa-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "medusa"
path = "src/main.rs"

[dependencies]
medusa-build = { path = "../medusa-build" }
medusa-config = { workspace = true }
medusa-control = { path = "../medusa-control" }
medusa-domain = { workspace = true }
medusa-eval = { path = "../medusa-eval" }
medusa-forge = { path = "../medusa-forge" }
medusa-store = { workspace = true }
medusa-web = { path = "../medusa-web" }
arc-swap = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
sd-notify = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
